# Generated by Django 2.2.5 on 2022-05-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwingBeatsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitored_detail',
            old_name='body_temperature',
            new_name='calories',
        ),
        migrations.RemoveField(
            model_name='monitored_detail',
            name='environment_temperature',
        ),
        migrations.RemoveField(
            model_name='monitored_detail',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='monitored_detail',
            name='reading',
        ),
        migrations.AddField(
            model_name='monitored_detail',
            name='steps',
            field=models.IntegerField(default='0000000', help_text='Enter the calories'),
        ),
        migrations.AlterField(
            model_name='monitored_detail',
            name='heart_rate',
            field=models.IntegerField(default='0000000', help_text='Enter the steps'),
        ),
    ]
