# Generated by Django 2.2.5 on 2022-05-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwingBeatsApp', '0002_auto_20220506_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitored_detail',
            name='blood_oxygen',
        ),
        migrations.AddField(
            model_name='monitored_detail',
            name='dance_duration',
            field=models.IntegerField(default='0000000', help_text='Enter the dance duration'),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(blank=True, default=0, help_text='Enter your weight in Kilograms'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='device_id',
            field=models.CharField(blank=True, help_text='Enter the Device ID', max_length=100),
        ),
    ]
